baseURL = "https://example.com/"
title = "E&W Trading Group"
enableRobotsTXT = true


[params]
  # site-wide params can be added here
  [params.analytics]
    [params.analytics.ga4]
      measurement_id = "G-Y5MR71RHK3"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
  pagerSize = 10
