baseURL = "https://example.com/"
title = "E&W Trading Group"
enableRobotsTXT = true
paginate = 10


[params]
  # site-wide params can be added here

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
